background {
    blur_passes = 3
    blur_size = 8
}
label {
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = rgba(ff3c00ff)
    font_size = 80
    position = 0, 120
    halign = center
    valign = center
}
