general {
    border_size = 0
    col.active_border = rgba(ff3c00ff) rgba(ff6a00ff)
    col.inactive_border = rgba(1a1a1f88)
}

decoration {
    rounding = 10
    blur {
        enabled = true
        size = 8
        passes = 3
        new_optimizations = true
    }
}
